spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # SQL? ?? ?? ???? ??? ???? ?????.
        format_sql: true
    # ???? SQL ??? ??? ?????.
    show-sql: true
    # ??? ?? ???? ??????. ?? Bean? ??? ?? ??? ??? ??????.
    defer-datasource-initialization: true